<?php
/**
 * FP Platform
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    FPPlatform
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class CityData {

	public $table = 'cities';

	public $records = array(
		array(
			'id' => '1',
			'created' => '2012-11-23 07:09:20',
			'modified' => '2012-11-24 00:18:55',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Chennai',
			'slug' => 'chennai',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '1',
			'language_id' => ''
		),
		array(
			'id' => '2',
			'created' => '2012-11-23 07:14:00',
			'modified' => '2012-11-23 07:14:00',
			'country_id' => '240',
			'state_id' => '2',
			'name' => 'Appanoose',
			'slug' => 'appanoose',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '3',
			'created' => '2012-11-23 09:11:06',
			'modified' => '2012-11-26 07:32:56',
			'country_id' => '240',
			'state_id' => '3',
			'name' => 'Providence',
			'slug' => 'providence',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '1',
			'language_id' => ''
		),
		array(
			'id' => '4',
			'created' => '2012-11-23 09:17:28',
			'modified' => '2012-11-23 09:17:28',
			'country_id' => '240',
			'state_id' => '4',
			'name' => 'Perry',
			'slug' => 'perry',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '5',
			'created' => '2012-11-23 09:23:26',
			'modified' => '2012-11-23 09:23:26',
			'country_id' => '143',
			'state_id' => '5',
			'name' => 'San Juan del R',
			'slug' => 'san-juan-del-r',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '6',
			'created' => '2012-11-23 09:36:30',
			'modified' => '2012-11-23 09:36:30',
			'country_id' => '103',
			'state_id' => '6',
			'name' => 'Jakarta',
			'slug' => 'jakarta',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '7',
			'created' => '2012-11-23 09:39:47',
			'modified' => '2012-11-23 09:39:47',
			'country_id' => '240',
			'state_id' => '7',
			'name' => 'Richmond',
			'slug' => 'richmond',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '8',
			'created' => '2012-11-23 09:50:25',
			'modified' => '2012-11-23 09:50:25',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Hinds',
			'slug' => 'hinds',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '9',
			'created' => '2012-11-23 09:52:33',
			'modified' => '2012-11-23 09:52:33',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Steele',
			'slug' => 'steele',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '10',
			'created' => '2012-11-23 10:02:18',
			'modified' => '2012-11-23 10:02:18',
			'country_id' => '15',
			'state_id' => '10',
			'name' => 'Muswellbrook',
			'slug' => 'muswellbrook',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '11',
			'created' => '2012-11-23 10:05:06',
			'modified' => '2012-11-23 10:05:06',
			'country_id' => '240',
			'state_id' => '4',
			'name' => 'Kosciusko',
			'slug' => 'kosciusko',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '12',
			'created' => '2012-11-23 10:06:30',
			'modified' => '2012-11-26 07:31:50',
			'country_id' => '240',
			'state_id' => '11',
			'name' => 'Hart',
			'slug' => 'hart',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '1',
			'language_id' => ''
		),
		array(
			'id' => '13',
			'created' => '2012-11-23 10:23:19',
			'modified' => '2012-11-23 10:23:19',
			'country_id' => '240',
			'state_id' => '12',
			'name' => 'Middlesex',
			'slug' => 'middlesex',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '14',
			'created' => '2012-11-23 10:29:14',
			'modified' => '2012-11-23 10:29:14',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Vitoria',
			'slug' => 'vitoria',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '15',
			'created' => '2012-11-23 10:40:29',
			'modified' => '2012-11-23 10:40:29',
			'country_id' => '219',
			'state_id' => '14',
			'name' => 'Trekanten',
			'slug' => 'trekanten',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '16',
			'created' => '2012-11-23 10:49:31',
			'modified' => '2012-11-23 10:49:31',
			'country_id' => '238',
			'state_id' => '15',
			'name' => 'Abu Dhabi',
			'slug' => 'abu-dhabi',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '17',
			'created' => '2012-11-23 10:52:59',
			'modified' => '2012-11-23 10:52:59',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Santa Clara',
			'slug' => 'santa-clara',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '18',
			'created' => '2012-11-24 00:45:46',
			'modified' => '2012-11-24 00:45:46',
			'country_id' => '32',
			'state_id' => '17',
			'name' => 'Gravata',
			'slug' => 'gravata',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '19',
			'created' => '2012-11-24 00:52:57',
			'modified' => '2012-11-24 00:52:57',
			'country_id' => '240',
			'state_id' => '18',
			'name' => 'Ulster',
			'slug' => 'ulster',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '20',
			'created' => '2012-11-24 00:58:43',
			'modified' => '2012-11-24 00:58:43',
			'country_id' => '240',
			'state_id' => '18',
			'name' => 'Erie',
			'slug' => 'erie',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '21',
			'created' => '2012-11-24 01:07:03',
			'modified' => '2012-11-26 07:33:05',
			'country_id' => '159',
			'state_id' => '19',
			'name' => 'Horotiu',
			'slug' => 'horotiu',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '1',
			'language_id' => ''
		),
		array(
			'id' => '22',
			'created' => '2012-11-24 01:19:29',
			'modified' => '2012-11-24 01:19:29',
			'country_id' => '156',
			'state_id' => '20',
			'name' => 'Huizen',
			'slug' => 'huizen',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '23',
			'created' => '2012-11-24 01:34:34',
			'modified' => '2012-11-24 01:34:34',
			'country_id' => '158',
			'state_id' => '21',
			'name' => 'Poya South',
			'slug' => 'poya-south',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '24',
			'created' => '2012-11-24 01:38:00',
			'modified' => '2012-11-24 01:38:00',
			'country_id' => '240',
			'state_id' => '22',
			'name' => 'Robeson',
			'slug' => 'robeson',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '25',
			'created' => '2012-11-24 01:41:15',
			'modified' => '2012-11-24 01:41:15',
			'country_id' => '96',
			'state_id' => '23',
			'name' => 'Gurgaon',
			'slug' => 'gurgaon',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '26',
			'created' => '2012-11-24 05:26:53',
			'modified' => '2012-11-24 05:26:53',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'San Andres Tuxtla',
			'slug' => 'san-andres-tuxtla',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '27',
			'created' => '2012-11-24 05:38:12',
			'modified' => '2012-11-24 05:38:12',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Santa Cruz',
			'slug' => 'santa-cruz',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '28',
			'created' => '2012-11-24 05:43:50',
			'modified' => '2012-11-24 05:43:50',
			'country_id' => '66',
			'state_id' => '26',
			'name' => 'Abdeen',
			'slug' => 'abdeen',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '29',
			'created' => '2012-11-24 05:55:27',
			'modified' => '2012-11-24 05:55:27',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Clay',
			'slug' => 'clay',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '30',
			'created' => '2012-11-24 06:08:04',
			'modified' => '2012-11-24 06:08:04',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Keweenaw',
			'slug' => 'keweenaw',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '31',
			'created' => '2012-11-24 06:13:54',
			'modified' => '2012-11-24 06:13:54',
			'country_id' => '219',
			'state_id' => '14',
			'name' => 'Kalmar ',
			'slug' => 'kalmar',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '32',
			'created' => '2012-11-24 06:19:30',
			'modified' => '2012-11-24 06:19:30',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Wake',
			'slug' => 'wake',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '33',
			'created' => '2012-11-24 06:39:22',
			'modified' => '2012-11-24 06:39:22',
			'country_id' => '240',
			'state_id' => '11',
			'name' => 'Emanuel',
			'slug' => 'emanuel',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '34',
			'created' => '2012-11-24 06:47:56',
			'modified' => '2012-11-26 07:31:57',
			'country_id' => '240',
			'state_id' => '16',
			'name' => 'Contra Costa',
			'slug' => 'contra-costa',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '1',
			'language_id' => ''
		),
		array(
			'id' => '35',
			'created' => '2012-11-24 07:02:38',
			'modified' => '2012-11-24 07:02:38',
			'country_id' => '240',
			'state_id' => '18',
			'name' => 'Suffolk',
			'slug' => 'suffolk',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '36',
			'created' => '2012-11-24 07:08:20',
			'modified' => '2012-11-24 07:08:20',
			'country_id' => '220',
			'state_id' => '29',
			'name' => 'Maloja District',
			'slug' => 'maloja-district',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '37',
			'created' => '2012-11-24 08:12:28',
			'modified' => '2012-11-24 08:12:28',
			'country_id' => '96',
			'state_id' => '30',
			'name' => 'Pali',
			'slug' => 'pali',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '38',
			'created' => '2012-11-24 08:16:51',
			'modified' => '2012-11-24 08:16:51',
			'country_id' => '4',
			'state_id' => '31',
			'name' => 'Oran',
			'slug' => 'oran',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '39',
			'created' => '2012-11-24 08:18:07',
			'modified' => '2012-11-24 08:18:07',
			'country_id' => '4',
			'state_id' => '32',
			'name' => 'M',
			'slug' => 'm',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '40',
			'created' => '2012-11-24 08:19:23',
			'modified' => '2012-11-24 08:19:23',
			'country_id' => '4',
			'state_id' => '33',
			'name' => 'El Khroub',
			'slug' => 'el-khroub',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '41',
			'created' => '2012-11-24 08:21:13',
			'modified' => '2012-11-24 08:21:13',
			'country_id' => '4',
			'state_id' => '34',
			'name' => 'Guelma',
			'slug' => 'guelma',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '42',
			'created' => '2012-11-26 00:46:45',
			'modified' => '2012-11-26 00:46:45',
			'country_id' => '96',
			'state_id' => '35',
			'name' => 'Rajkot',
			'slug' => 'rajkot',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '43',
			'created' => '2012-11-26 01:06:46',
			'modified' => '2012-11-26 01:06:46',
			'country_id' => '42',
			'state_id' => '36',
			'name' => 'Joao Teves',
			'slug' => 'joao-teves',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '44',
			'created' => '2012-11-26 01:24:26',
			'modified' => '2012-11-26 01:24:26',
			'country_id' => '124',
			'state_id' => '37',
			'name' => 'Peka',
			'slug' => 'peka',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '45',
			'created' => '2012-11-26 01:34:31',
			'modified' => '2012-11-26 01:34:31',
			'country_id' => '124',
			'state_id' => '38',
			'name' => 'Hlotse',
			'slug' => 'hlotse',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '46',
			'created' => '2012-11-26 01:38:54',
			'modified' => '2012-11-26 01:38:54',
			'country_id' => '80',
			'state_id' => '39',
			'name' => 'Zadie',
			'slug' => 'zadie',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '47',
			'created' => '2012-11-26 01:40:44',
			'modified' => '2012-11-26 01:40:44',
			'country_id' => '225',
			'state_id' => '40',
			'name' => 'Phipun',
			'slug' => 'phipun',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '48',
			'created' => '2012-11-26 02:02:12',
			'modified' => '2012-11-26 02:02:12',
			'country_id' => '80',
			'state_id' => '41',
			'name' => 'Lastoursville',
			'slug' => 'lastoursville',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '49',
			'created' => '2012-11-26 02:03:28',
			'modified' => '2012-11-26 02:03:28',
			'country_id' => '80',
			'state_id' => '42',
			'name' => 'Woleu',
			'slug' => 'woleu',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '50',
			'created' => '2012-11-26 02:17:45',
			'modified' => '2012-11-26 02:17:45',
			'country_id' => '80',
			'state_id' => '43',
			'name' => 'Ndougou',
			'slug' => 'ndougou',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '51',
			'created' => '2012-11-26 02:19:33',
			'modified' => '2012-11-26 02:19:33',
			'country_id' => '76',
			'state_id' => '44',
			'name' => 'Haute-Garonne',
			'slug' => 'haute-garonne',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '52',
			'created' => '2012-11-26 02:20:50',
			'modified' => '2012-11-26 02:20:50',
			'country_id' => '240',
			'state_id' => '45',
			'name' => 'Lawrence',
			'slug' => 'lawrence',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '53',
			'created' => '2012-11-26 02:34:54',
			'modified' => '2012-11-26 02:34:54',
			'country_id' => '250',
			'state_id' => '46',
			'name' => 'Sana\'a',
			'slug' => 'sana-a',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '54',
			'created' => '2012-11-26 02:36:46',
			'modified' => '2012-11-26 02:36:46',
			'country_id' => '174',
			'state_id' => '47',
			'name' => 'San Estanislao',
			'slug' => 'san-estanislao',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '55',
			'created' => '2012-11-26 02:40:11',
			'modified' => '2012-11-26 02:40:11',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Gran Sabana',
			'slug' => 'gran-sabana',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '56',
			'created' => '2012-11-26 02:50:33',
			'modified' => '2012-11-26 02:50:33',
			'country_id' => '240',
			'state_id' => '27',
			'name' => 'Conway',
			'slug' => 'conway',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '57',
			'created' => '2012-11-26 02:53:53',
			'modified' => '2012-11-26 02:53:53',
			'country_id' => '240',
			'state_id' => '49',
			'name' => 'Arapahoe',
			'slug' => 'arapahoe',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '58',
			'created' => '2012-11-26 03:07:06',
			'modified' => '2012-11-26 03:07:06',
			'country_id' => '96',
			'state_id' => '50',
			'name' => 'Himalaya',
			'slug' => 'himalaya',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '59',
			'created' => '2012-11-26 03:09:05',
			'modified' => '2012-11-26 03:09:05',
			'country_id' => '240',
			'state_id' => '51',
			'name' => 'King',
			'slug' => 'king',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '60',
			'created' => '2012-11-26 03:16:05',
			'modified' => '2012-11-26 03:16:05',
			'country_id' => '88',
			'state_id' => '52',
			'name' => 'Rockersweg',
			'slug' => 'rockersweg',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '61',
			'created' => '2012-11-26 04:40:39',
			'modified' => '2012-11-26 04:40:39',
			'country_id' => '57',
			'state_id' => '53',
			'name' => 'Orounda',
			'slug' => 'orounda',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '62',
			'created' => '2012-11-26 04:44:45',
			'modified' => '2012-11-26 04:44:45',
			'country_id' => '50',
			'state_id' => '54',
			'name' => 'Man',
			'slug' => 'man',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '63',
			'created' => '2012-11-26 04:47:34',
			'modified' => '2012-11-26 04:47:34',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'San Diego',
			'slug' => 'san-diego',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '64',
			'created' => '2012-11-26 04:50:48',
			'modified' => '2012-11-26 04:50:48',
			'country_id' => '240',
			'state_id' => '18',
			'name' => 'Kings',
			'slug' => 'kings',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '65',
			'created' => '2012-11-26 04:56:11',
			'modified' => '2012-11-26 04:56:11',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Birmingham',
			'slug' => 'birmingham',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '66',
			'created' => '2012-11-26 06:44:56',
			'modified' => '2012-11-26 06:44:56',
			'country_id' => '106',
			'state_id' => '56',
			'name' => 'Dun Laoghaire-Rathdown',
			'slug' => 'dun-laoghaire-rathdown',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
		array(
			'id' => '67',
			'created' => '2012-12-19 12:51:57',
			'modified' => '2012-12-19 12:51:57',
			'country_id' => '0',
			'state_id' => '0',
			'name' => 'Bangalore',
			'slug' => 'bangalore',
			'latitude' => '',
			'longitude' => '',
			'timezone' => '',
			'dma_id' => '',
			'county' => '',
			'code' => '',
			'is_approved' => '',
			'language_id' => ''
		),
	);

}
