<?php
/**
 * FP Platform
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    FPPlatform
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class UserData {

	public $table = 'users';

	public $records = array(
		array(
			'id' => '1',
			'created' => '2010-06-04 04:57:21',
			'modified' => '2013-12-17 14:30:56',
			'role_id' => '1',
			'username' => 'admin',
			'email' => 'productdemo.admin+admin@gmail.com',
			'password' => '$1$LD_q_\"]u$8S/FbPxV6Y.LAVUVKlNJg.',
			'referred_by_user_id' => '',
			'fb_user_id' => '0',
			'fb_access_token' => '',
			'user_openid_count' => '0',
			'user_login_count' => '0',
			'user_view_count' => '0',
			'job_count' => '0',
			'active_job_count' => '0',
			'job_favorite_count' => '0',
			'job_feedback_count' => '0',
			'positive_feedback_count' => '0',
			'job_flag_count' => '0',
			'job_view_count' => '0',
			'request_flag_count' => '0',
			'request_view_count' => '0',
			'cookie_hash' => '0682b4ee5683deadfc5c3d56d73e947f',
			'cookie_time_modified' => '2011-01-23 10:58:32',
			'is_openid_register' => '',
			'is_gmail_register' => '',
			'is_yahoo_register' => '',
			'is_agree_terms_conditions' => '1',
			'is_active' => '1',
			'is_email_confirmed' => '1',
			'is_affiliate_user' => '',
			'ip_id' => '',
			'last_login_ip_id' => '',
			'signup_ip' => '127.0.0.1',
			'last_login_ip' => '127.0.0.1',
			'last_logged_in_time' => '2013-12-24 14:22:27',
			'available_balance_amount' => '0',
			'available_purchase_amount' => '0',
			'blocked_amount' => '0',
			'status_message' => '',
			'cleared_amount' => '0',
			'cleared_blocked_amount' => '0',
			'total_commission_pending_amount' => '0',
			'total_commission_canceled_amount' => '0',
			'total_commission_completed_amount' => '0',
			'total_amount_withdrawn' => '0',
			'total_withdraw_request_count' => '0',
			'commission_line_amount' => '0',
			'commission_withdraw_request_amount' => '0',
			'commission_paid_amount' => '0',
			'available_wallet_amount' => '0',
			'twitter_access_token' => '',
			'twitter_access_key' => '',
			'twitter_user_id' => '0',
			'site_state_id' => '0',
			'sudopay_pay_key' => '',
			'sudopay_payment_id' => '0',
			'sudopay_gateway_id' => '0',
			'sudopay_receiver_account_id' => '0',
			'user_avatar_source_id' => '0',
			'user_referred_count' => '0',
			'last_sent_inactive_mail' => '2013-12-09 02:51:48',
			'sent_inactive_mail_count' => '0',
			'referred_purchase_count' => '0',
			'affiliate_refer_purchase_count' => '0',
			'referred_by_user_count' => '0',
			'sales_cleared_count' => '0',
			'sales_cleared_amount' => '0',
			'sales_pipeline_count' => '0',
			'sales_pipeline_amount' => '0',
			'sales_lost_count' => '0',
			'sales_lost_amount' => '0',
			'request_count' => '0',
			'request_favorite_count' => '0',
			'in_progress_overtime_meet_count' => '0',
			'order_received_count' => '0',
			'order_accepted_count' => '0',
			'order_success_without_overtime_count' => '0',
			'order_success_with_overtime_count' => '0',
			'order_failure_count' => '0',
			'order_active_count' => '0',
			'order_last_accepted_date' => '',
			'buyer_order_purchase_count' => '0',
			'buyer_order_sucess_without_overtime_count' => '0',
			'buyer_order_sucess_with_overtime_count' => '0',
			'buyer_order_active_count' => '0',
			'buyer_waiting_for_acceptance_count' => '0',
			'buyer_in_progress_count' => '0',
			'buyer_in_progress_overtime_count' => '0',
			'buyer_review_count' => '0',
			'buyer_completed_count' => '0',
			'buyer_cancelled_count' => '0',
			'buyer_rejected_count' => '0',
			'buyer_cancelled_late_order_count' => '0',
			'buyer_expired_count' => '0',
			'buyer_redeliver_count' => '0',
			'buyer_payment_pending_count' => '0',
			'seller_waiting_for_acceptance' => '0',
			'seller_in_progress_count' => '0',
			'seller_in_progress_overtime_count' => '0',
			'seller_review_count' => '0',
			'seller_completed_count' => '0',
			'seller_rejected_count' => '0',
			'seller_cancelled_count' => '0',
			'seller_expired_count' => '0',
			'seller_redeliver_count' => '0',
			'mean_rating' => '0',
			'actual_rating' => '0',
			'linkedin_user_id' => '',
			'linkedin_access_token' => '',
			'is_linkedin_register' => '0',
			'openid_user_id' => '',
			'google_user_id' => '',
			'google_access_token' => '',
			'yahoo_user_id' => '',
			'yahoo_access_token' => '',
			'is_google_connected' => '',
			'is_yahoo_connected' => '',
			'is_linkedin_connected' => '',
			'pwd_reset_token' => '',
			'pwd_reset_requested_date' => '1970-01-01 00:00:00',
			'security_question_id' => '0',
			'security_answer' => '',
			'fb_friends_count' => '0',
			'twitter_followers_count' => '0',
			'linkedin_contacts_count' => '0',
			'google_contacts_count' => '0',
			'yahoo_contacts_count' => '0',
			'is_skipped_fb' => '1',
			'is_skipped_twitter' => '1',
			'is_skipped_linkedin' => '',
			'is_skipped_google' => '1',
			'is_skipped_yahoo' => '1',
			'googleplus_user_id' => '',
			'is_googleplus_connected' => '',
			'googleplus_contacts_count' => '0',
			'googleplus_avatar_url' => '',
			'google_avatar_url' => '',
			'linkedin_avatar_url' => '',
			'is_facebook_connected' => '',
			'is_facebook_register' => '',
			'facebook_access_token' => '',
			'facebook_user_id' => '',
			'purchase_cleared_amount' => '0',
			'purchase_cleared_count' => '0',
			'purchase_pipeline_amount' => '0',
			'purchase_pipeline_count' => '0',
			'purchase_lost_amount' => '0',
			'purchase_lost_count' => '0',
			'is_twitter_register' => '',
			'is_twitter_connected' => '',
			'twitter_avatar_url' => '',
			'activity_message_id' => '0',
			'is_idle' => '',
			'is_job_posted' => '1',
			'is_job_requested' => '',
			'is_engaged' => '',
			'is_googleplus_register' => '',
			'is_google_register' => '',
			'sudopay_payment_gateways_user_count' => '0',
			'buyer_mutual_cancelled_count' => '0',
			'seller_mutual_cancelled_count' => '0'
		),
	);

}
