<?php
/**
 * FP Platform
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    FPPlatform
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class SettingData
{
    public $table = 'settings';
    public $records = array(
        array(
            'id' => '1',
            'setting_category_id' => '54',
            'setting_category_parent_id' => '1',
            'name' => 'site.name',
            'value' => 'FPPlatform',
            'description' => 'You can make changes in site name by using this value. ',
            'type' => 'text',
            'options' => '',
            'label' => 'Site Name',
            'order' => '1',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '2',
            'setting_category_id' => '1',
            'setting_category_parent_id' => '0',
            'name' => 'site.version',
            'value' => 'v2.0b1',
            'description' => 'It specifies the version of the site.',
            'type' => 'text',
            'options' => '',
            'label' => 'Site Version',
            'order' => '3',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '3',
            'setting_category_id' => '45',
            'setting_category_parent_id' => '2',
            'name' => 'meta.keywords',
            'value' => 'agriya, dev1',
            'description' => 'You can make changes in meta keywords.',
            'type' => 'text',
            'options' => '',
            'label' => 'Meta Keywords',
            'order' => '1',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '4',
            'setting_category_id' => '45',
            'setting_category_parent_id' => '2',
            'name' => 'meta.description',
            'value' => 'FPPlatform',
            'description' => 'You can make changes in meta description.',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Meta Description',
            'order' => '2',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '5',
            'setting_category_id' => '43',
            'setting_category_parent_id' => '1',
            'name' => 'site.admin_email',
            'value' => 'productdemo.admin+adminemail+fpplatform@gmail.com',
            'description' => 'You\'ll receive email to this address, when somebody post a contact form and site notifications',
            'type' => 'text',
            'options' => '',
            'label' => 'Admin email address',
            'order' => '11',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '52',
            'setting_category_id' => '43',
            'setting_category_parent_id' => '1',
            'name' => 'site.noreply_email',
            'value' => '',
            'description' => 'this is from address, its using in bulk email sending option.',
            'type' => 'text',
            'options' => '',
            'label' => 'Noreply Email address',
            'order' => '12',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '9',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.using_to_login',
            'value' => 'username',
            'description' => 'You can select the option from the drop-downs to login into the site',
            'type' => 'select',
            'options' => 'username, email',
            'label' => 'Option for logging into the site',
            'order' => '1',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '10',
            'setting_category_id' => '46',
            'setting_category_parent_id' => '2',
            'name' => 'site.tracking_script',
            'value' => '<script type=\"text/javascript\">var gaJsHost=((\"https:\"==document.location.protocol)?\"https://ssl.\":\"http://www.\");document.write(unescape(\"%3Cscript src=\\\'\"+gaJsHost+\"google-analytics.com/ga.js\\\' type=\\\'text/javascript\\\'%3E%3C/script%3E\"));</script><script type=\"text/javascript\">var pageTracker=_gat._getTracker(\"UA-4819298-1\");pageTracker._initData();pageTracker._trackPageview();</script>',
            'description' => 'You can update the site tracker script like google analytics.  ',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Site tracker',
            'order' => '26',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '16',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.content_length',
            'value' => '50',
            'description' => 'Number of message characters to display in inbox.',
            'type' => 'text',
            'options' => '',
            'label' => 'Message content length',
            'order' => '6',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '18',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.page_size',
            'value' => '20',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Message page size',
            'order' => '7',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '19',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.listing_element_cache_duration',
            'value' => '75 sec',
            'description' => 'Cache time for messages side bar links',
            'type' => 'text',
            'options' => '',
            'label' => 'Cache time for messages side bar links',
            'order' => '8',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '20',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.is_send_email_on_new_message',
            'value' => '1',
            'description' => 'If blocked, the external mail could not be sent',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Allow users to send external messages',
            'order' => '2',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '21',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.allowed_message_size',
            'value' => '2',
            'description' => 'Allowed message size for user',
            'type' => 'text',
            'options' => '',
            'label' => 'Allowed message size',
            'order' => '9',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '22',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.allowed_message_size_unit',
            'value' => 'MB',
            'description' => 'Allowed message size unit for user.',
            'type' => 'select',
            'options' => 'MB, KB, GB, B',
            'label' => 'Allowed message size unit',
            'order' => '10',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '25',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.micro_thumb.width',
            'value' => '18',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Micro thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '26',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.micro_thumb.height',
            'value' => '18',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '27',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.small_thumb.width',
            'value' => '48',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Small thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '28',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.small_thumb.height',
            'value' => '48',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '29',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.medium_thumb.width',
            'value' => '56',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Medium thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '30',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.medium_thumb.height',
            'value' => '56',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '31',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.normal_thumb.width',
            'value' => '102',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Normal thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '32',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.normal_thumb.height',
            'value' => '72',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '33',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.big_thumb.width',
            'value' => '126',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Big thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '34',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.big_thumb.height',
            'value' => '86',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '35',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.small_big_thumb.width',
            'value' => '80',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Small big thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '36',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.small_big_thumb.height',
            'value' => '80',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '37',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.medium_big_thumb.width',
            'value' => '354',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Medium big thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '38',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.medium_big_thumb.height',
            'value' => '274',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '39',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.very_big_thumb.width',
            'value' => '1400',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Very big thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '40',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.very_big_thumb.height',
            'value' => '556',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '41',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.is_admin_activate_after_register',
            'value' => '0',
            'description' => 'Allow admin to activate the user or not after registration.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Admin activation after registration',
            'order' => '3',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '42',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.is_email_verification_for_register',
            'value' => '0',
            'description' => 'Specify email verification for an user required or not.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Email verification for register',
            'order' => '4',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '43',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.is_auto_login_after_register',
            'value' => '1',
            'description' => 'Allow user to automatically login or not after registration. This will have effect only if email verification and admin activation settings are disabled.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Auto login after register',
            'order' => '5',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '44',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.is_admin_mail_after_register',
            'value' => '1',
            'description' => 'Notification for admin required or not, once the user has been registered.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Admin notification mail after user\'s registration',
            'order' => '6',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '45',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.is_welcome_mail_after_register',
            'value' => '1',
            'description' => 'Welcome mail should be delivered to the user are not after successful activation.
',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Welcome mail after registration',
            'order' => '7',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '46',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.is_allow_send_messsage',
            'value' => '1',
            'description' => 'Allow to send message.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Allow send message',
            'order' => '5',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '47',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.is_logout_after_change_password',
            'value' => '1',
            'description' => 'Should be logged out after changing password or not.

',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'logout after password change',
            'order' => '8',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '56',
            'setting_category_id' => '44',
            'setting_category_parent_id' => '52',
            'name' => 'site.date.format',
            'value' => '%b %d, %Y',
            'description' => 'You can make changes in date format of the site.',
            'type' => 'text',
            'options' => '',
            'label' => 'Date Format',
            'order' => '17',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '57',
            'setting_category_id' => '44',
            'setting_category_parent_id' => '52',
            'name' => 'site.datetime.format',
            'value' => '%b %d, %Y %I:%M %p',
            'description' => 'You can make changes in date time format of the site.',
            'type' => 'text',
            'options' => '',
            'label' => 'Date Time Format',
            'order' => '19',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '58',
            'setting_category_id' => '44',
            'setting_category_parent_id' => '52',
            'name' => 'site.time.format',
            'value' => '%I:%M %p',
            'description' => 'You can make changes in time format of the site.',
            'type' => 'text',
            'options' => '',
            'label' => 'Time Format',
            'order' => '18',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '59',
            'setting_category_id' => '44',
            'setting_category_parent_id' => '52',
            'name' => 'site.date.tooltip',
            'value' => '%b %d, %Y %I:%M %p',
            'description' => 'You can make changes in date format tooltip of the site.',
            'type' => 'text',
            'options' => '',
            'label' => 'Date Format Tooltip',
            'order' => '20',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '60',
            'setting_category_id' => '44',
            'setting_category_parent_id' => '52',
            'name' => 'site.time.tooltip',
            'value' => '%B %d, %Y (%A) %Z',
            'description' => 'You can change your time format tooltip of your site using this value',
            'type' => 'text',
            'options' => '',
            'label' => 'Time Format Tooltip',
            'order' => '21',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '61',
            'setting_category_id' => '44',
            'setting_category_parent_id' => '52',
            'name' => 'site.datetime.tooltip',
            'value' => '%B %d, %Y %I:%M:%S %p (%A) %Z',
            'description' => 'You can change your date time tooltip of your site using this value.',
            'type' => 'text',
            'options' => '',
            'label' => 'Date Time Tooltip',
            'order' => '22',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '71',
            'setting_category_id' => '57',
            'setting_category_parent_id' => '22',
            'name' => 'site.maintenance_mode',
            'value' => '0',
            'description' => 'Site maintenance mode. If its checked, users can not access site. Only admin can access his  page.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Maintenance mode',
            'order' => '29',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '72',
            'setting_category_id' => '55',
            'setting_category_parent_id' => '52',
            'name' => 'site.language',
            'value' => 'en',
            'description' => 'Site language',
            'type' => 'select',
            'options' => '',
            'label' => 'Site language ',
            'order' => '4',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '73',
            'setting_category_id' => '46',
            'setting_category_parent_id' => '2',
            'name' => 'site.robots',
            'value' => '',
            'description' => 'Content for robots.txt. Refer, http://www.robotstxt.org/',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Robots',
            'order' => '27',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '92',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.is_allow_user_to_switch_language',
            'value' => '1',
            'description' => 'Allow user to switch language',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Allow user to switch language',
            'order' => '14',
            'plugin_name' => 'Translation'
        ) ,
        array(
            'id' => '160',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.price',
            'value' => '5,10,15,20',
            'description' => 'Price for a job.
Comma separated for multiple amounts.',
            'type' => 'text',
            'options' => '',
            'label' => 'Job Price',
            'order' => '4',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '161',
            'setting_category_id' => '56',
            'setting_category_parent_id' => '52',
            'name' => 'site.currency',
            'value' => '$',
            'description' => 'Currency for the site',
            'type' => 'text',
            'options' => '',
            'label' => 'Site Currency',
            'order' => '6',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '162',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.days_after_amount_withdraw',
            'value' => '0',
            'description' => 'The total number of days after which the amount will be in cleared state.',
            'type' => 'text',
            'options' => '',
            'label' => 'Days after amount will be cleared',
            'order' => '23',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '121',
            'setting_category_id' => '40',
            'setting_category_parent_id' => '58',
            'name' => 'facebook.is_enabled_facebook_connect',
            'value' => '1',
            'description' => 'By enabling this feature, users can authenticate their ##SITE_NAME## account using facebook',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable facebook login',
            'order' => '1',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '122',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'facebook.api_key',
            'value' => '0d5427d06aaa9797bec70322b54e5274',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Facebook API Key',
            'order' => '0',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '123',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'facebook.secrect_key',
            'value' => 'c21853ffc7620d2faa694f9ebdeb0efa',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Facebook Secret Key',
            'order' => '1',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '159',
            'setting_category_id' => '44',
            'setting_category_parent_id' => '52',
            'name' => 'site.datetimehighlight.tooltip',
            'value' => '%B %d, %Y %I:%M:%S %p (%A) %Z',
            'description' => 'You can change your datetimehighlight tooltip of your site using this value.',
            'type' => 'text',
            'options' => '',
            'label' => 'Date Time Highlight Tooltip',
            'order' => '23',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '169',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.commission_amount',
            'value' => '1,2,3,4',
            'description' => 'Comma separated for multiple Commission amounts, taken for every job purchase.
Note: 
The number of comma separated commission amount must exactly match the number of comma separated job amount given.
',
            'type' => 'text',
            'options' => '',
            'label' => 'Commission amount',
            'order' => '5',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '172',
            'setting_category_id' => '56',
            'setting_category_parent_id' => '52',
            'name' => 'site.currency_code',
            'value' => 'USD',
            'description' => '',
            'type' => 'select',
            'options' => 'AUD,BRL,CAD,CZK,DKK,EUR,HKD,HUF,ILS,JPY,MXN,NOK,NZD,PHP,PLN,GBP,SGD,SEK,CHF,TWD,THB,USD ',
            'label' => 'Site Currency Code',
            'order' => '5',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '176',
            'setting_category_id' => '6',
            'setting_category_parent_id' => '41',
            'name' => 'twitter.consumer_key',
            'value' => 'G3jbsEoLWb9Qqu570xCYsQ',
            'description' => 'Consumer key for twitter',
            'type' => 'text',
            'options' => '',
            'label' => 'Consumer key',
            'order' => '4',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '177',
            'setting_category_id' => '6',
            'setting_category_parent_id' => '41',
            'name' => 'twitter.consumer_secret',
            'value' => 'qwj13qzE4Lk12NYzj7yvwTmZjmSLrEj6fa7UKmtAU',
            'description' => 'Secret key for twitter',
            'type' => 'text',
            'options' => '',
            'label' => 'Consumer secret',
            'order' => '5',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '178',
            'setting_category_id' => '6',
            'setting_category_parent_id' => '41',
            'name' => 'twitter.site_username',
            'value' => 'fpplatform',
            'description' => '\'Follow me\' twitter name.',
            'type' => 'text',
            'options' => '',
            'label' => 'Twitter username',
            'order' => '11',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '179',
            'setting_category_id' => '6',
            'setting_category_parent_id' => '41',
            'name' => 'twitter.site_user_access_key',
            'value' => 'IDhDmyAQcMHUwI2sC6IBSrhiHpxRO7ae0x4KG2yro',
            'description' => 'access key for twitter to post url',
            'type' => 'text',
            'options' => '',
            'label' => 'Access key',
            'order' => '6',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '180',
            'setting_category_id' => '6',
            'setting_category_parent_id' => '41',
            'name' => 'twitter.site_user_access_token',
            'value' => '364130821-lF4XAQhMQTm0fxqWIi3hhGVBNX7cBduFdpEURIy6',
            'description' => 'Access token for twitter for post',
            'type' => 'text',
            'options' => '',
            'label' => 'Access token',
            'order' => '7',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '181',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.auto_expire',
            'value' => '1',
            'description' => 'Days after in which unaccepted jobs are automatically canceled.',
            'type' => 'text',
            'options' => '',
            'label' => 'Auto expire',
            'order' => '20',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '183',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.is_send_internal_message',
            'value' => '1',
            'description' => 'If blocked, the internal and automatic messages could not be sent',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Allow users to send internal messages',
            'order' => '1',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '184',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'job.post_job_on_facebook',
            'value' => '1',
            'description' => 'Automatically post newly added jobs in site Facebook Wall',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Auto post on Site Facebook wall',
            'order' => '6',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '185',
            'setting_category_id' => '6',
            'setting_category_parent_id' => '41',
            'name' => 'job.post_job_on_twitter',
            'value' => '1',
            'description' => 'Automatically post newly added jobs in Site Twitter Wall',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Auto post on Site Twitter',
            'order' => '8',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '190',
            'setting_category_id' => '6',
            'setting_category_parent_id' => '41',
            'name' => 'social_networking.post_job_on_user_twitter',
            'value' => '1',
            'description' => 'Automatically post newly added jobs in users Twitter wall.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Auto post on User Twitter',
            'order' => '9',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '188',
            'setting_category_id' => '3',
            'setting_category_parent_id' => '58',
            'name' => 'user.notification_for_inactive_users',
            'value' => '15',
            'description' => 'Notification will be sent if the user is inactive for the days set.
(value is in days).
',
            'type' => 'text',
            'options' => '',
            'label' => 'Notification for inactive users',
            'order' => '15',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '191',
            'setting_category_id' => '54',
            'setting_category_parent_id' => '1',
            'name' => 'site.element_cache_duration',
            'value' => '30',
            'description' => 'Cache duration set for elements in sec(s)',
            'type' => 'text',
            'options' => '',
            'label' => 'Element cache duration',
            'order' => '28',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '194',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.maximum_title_length',
            'value' => '200',
            'description' => 'Maximum character allowed for the job title',
            'type' => 'text',
            'options' => '',
            'label' => 'Job - Maximum title length',
            'order' => '11',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '195',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.maximum_description_length',
            'value' => '1000',
            'description' => 'Maximum character allowed for the job description',
            'type' => 'text',
            'options' => '',
            'label' => 'Job - Maximum description length',
            'order' => '13',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '202',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.minimum_title_length',
            'value' => '8',
            'description' => 'Minimum character allowed for the job title',
            'type' => 'text',
            'options' => '',
            'label' => 'Job - Minimum title length',
            'order' => '12',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '203',
            'setting_category_id' => '66',
            'setting_category_parent_id' => '16',
            'name' => 'suspicious_detector.suspiciouswords',
            'value' => 'stupid
fool
\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*([,;]\\s*\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*)*
^0[234679]{1}[\\s]{0,1}[\\-]{0,1}[\\s]{0,1}[1-9]{1}[0-9]{6}$
',
            'description' => 'The suspicious words given will be matched with user given message and will be auto flagged if such words are found.
(Note: Suspicious detection will be checked during Job creation and in contacting other users.Detection words should be newline separated.)',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Suspicious words',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '204',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'facebook.prompt_for_email_after_register',
            'value' => '1',
            'description' => 'Prompts facebook user to enter email after facebook registration.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Prompt for email after registration',
            'order' => '7',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '206',
            'setting_category_id' => '6',
            'setting_category_parent_id' => '41',
            'name' => 'twitter.prompt_for_email_after_register',
            'value' => '1',
            'description' => 'Prompts twitter user to enter email after twitter registration.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Prompt for email after registration',
            'order' => '10',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '207',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.days_in_progress_to_overtime',
            'value' => '3',
            'description' => 'When order is in-progress status and it exceeds in-progress (no.of.days) + in-progress overtime set days, it should 
change as in-progress-overtime status.',
            'type' => 'text',
            'options' => '',
            'label' => 'In progress overtime',
            'order' => '21',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '208',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.auto_review_complete',
            'value' => '2',
            'description' => 'If buyer didn\'t give review after the completion date by the seller and exceeds the specified date, the order will be completed automatically.',
            'type' => 'text',
            'options' => '',
            'label' => 'Auto review complete',
            'order' => '22',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '212',
            'setting_category_id' => '54',
            'setting_category_parent_id' => '1',
            'name' => 'site.slogan',
            'value' => 'The marketplace for ##JOB_PRICE##',
            'description' => 'Slogan text that appears in site and in email templates, allowed variable ##JOB_PRICE## ',
            'type' => 'text',
            'options' => '',
            'label' => 'Site Slogan',
            'order' => '2',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '213',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.commission_type',
            'value' => 'amount',
            'description' => 'Select the commission type.
If type is set to percentage, the commission amount given should be less than 100 percentage.
If type is amount, the commission amount given should be less than the corresponding job price.',
            'type' => 'select',
            'options' => 'amount,percentage',
            'label' => 'Commission type',
            'order' => '6',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '214',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.job_alternate_name',
            'value' => 'jobs',
            'description' => 'Job alternate name should be in English without Space',
            'type' => 'text',
            'options' => '',
            'label' => 'Job alternate name',
            'order' => '7',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '216',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.auto_suspend_job_on_system_flag',
            'value' => '1',
            'description' => 'Allow suspicious word detector to suspend the work automatically.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Auto suspend jobs on system flag',
            'order' => '26',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '217',
            'setting_category_id' => '5',
            'setting_category_parent_id' => '4',
            'name' => 'messages.send_notification_mail_for_sender',
            'value' => '1',
            'description' => 'Send a mail back to the person who sends a mail during order stage for their reference.
',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Send notification mail for sender',
            'order' => '3',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '219',
            'setting_category_id' => '43',
            'setting_category_parent_id' => '1',
            'name' => 'site.from_email',
            'value' => 'productdemo.admin+noreply+fpplatform@gmail.com',
            'description' => ' You can change this email address so that \'From\' email will be changed in all email communication.',
            'type' => 'text',
            'options' => '',
            'label' => 'From Email Address',
            'order' => '13',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '220',
            'setting_category_id' => '43',
            'setting_category_parent_id' => '1',
            'name' => 'site.reply_to_email',
            'value' => '',
            'description' => 'You can make changes in reply to email address using this value.',
            'type' => 'text',
            'options' => '',
            'label' => 'Reply To Email Address',
            'order' => '14',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '221',
            'setting_category_id' => '56',
            'setting_category_parent_id' => '52',
            'name' => 'site.currency_symbol_place',
            'value' => 'left',
            'description' => 'Whether to display currency symbol in left side of the currency or right side.',
            'type' => 'select',
            'options' => 'left,right',
            'label' => 'Site Currency position',
            'order' => '7',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '224',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'facebook.fb_access_token',
            'value' => '167730459941488|ff21848682c48e022dc54976-100000235263789|IW6Hv72GjBIV-czTcehUPl8U1t0',
            'description' => 'Facebook Accees Token. Please Click on Update Facebook Credentials to to update this Field',
            'type' => 'text',
            'options' => '',
            'label' => 'Facebook Accees Token',
            'order' => '4',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '225',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'facebook.fb_user_id',
            'value' => '100000235263789',
            'description' => '',
            'type' => 'text',
            'options' => 'Facebook User ID. Please Click on Update Facebook Credentials to to update this Field',
            'label' => 'Facebook User Id',
            'order' => '5',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '228',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.rating_type',
            'value' => 'percentage',
            'description' => 'Select the rating type.
Percentage will show ratings in percentage of positive ratings.
Count will show positive thumb up and negative thumb down count separately.
',
            'type' => 'select',
            'options' => 'percentage, count',
            'label' => 'Rating type',
            'order' => '19',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '229',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'facebook.app_id',
            'value' => '167730459941488',
            'description' => 'Facebook Application ID',
            'type' => 'text',
            'options' => '',
            'label' => 'Facebook Application Id',
            'order' => '2',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '233',
            'setting_category_id' => '57',
            'setting_category_parent_id' => '22',
            'name' => 'site.look_up_url',
            'value' => 'http://whois.sc/',
            'description' => 'Whois Look up URL to find IP details',
            'type' => 'text',
            'options' => 'text',
            'label' => 'Whois Look up URL',
            'order' => '15',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '239',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.min_days',
            'value' => '1',
            'description' => 'Minimum days allowed for the job completion',
            'type' => 'text',
            'options' => '',
            'label' => 'Job - Minimum days',
            'order' => '14',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '240',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.max_days',
            'value' => '20',
            'description' => 'Maximum days allowed for the job completion',
            'type' => 'text',
            'options' => '',
            'label' => 'Job - Maximum days',
            'order' => '15',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '241',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.default_job_radius_units',
            'value' => 'KM',
            'description' => 'Default radius units',
            'type' => 'select',
            'options' => 'MI, KM',
            'label' => 'Default radius unit',
            'order' => '18',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '244',
            'setting_category_id' => '43',
            'setting_category_parent_id' => '1',
            'name' => 'site.mobile_validation',
            'value' => '/^((\\+)?(\\d{2})[-])?(([\\(])?((\\d){3,5})([\\)])?[-])|(\\d{3,5})(\\d{5,8}){1}?$/',
            'description' => 'Common valiation for mobile number through out the site',
            'type' => 'text',
            'options' => '',
            'label' => 'Commom mobile validation',
            'order' => '21',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '245',
            'setting_category_id' => '64',
            'setting_category_parent_id' => '17',
            'name' => 'request.request_alternate_name',
            'value' => 'requests',
            'description' => 'Alternate name for request.',
            'type' => 'text',
            'options' => '',
            'label' => 'Request alternate name',
            'order' => '1',
            'plugin_name' => 'Requests'
        ) ,
        array(
            'id' => '246',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.job_coverage_radius_units',
            'value' => '100',
            'description' => 'Dafult value for job coverage radius ',
            'type' => 'text',
            'options' => '',
            'label' => 'Job Coverage Radius',
            'order' => '17',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '247',
            'setting_category_id' => '64',
            'setting_category_parent_id' => '17',
            'name' => 'request.is_admin_request_auto_approval',
            'value' => '1',
            'description' => 'Admin can approved or unapproved for newly added requests.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Admin auto approved request',
            'order' => '3',
            'plugin_name' => 'Requests'
        ) ,
        array(
            'id' => '248',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.is_admin_job_auto_approval',
            'value' => '0',
            'description' => 'Admin can approved or unapproved for newly added jobs.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Admin auto approved job',
            'order' => '24',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '249',
            'setting_category_id' => '64',
            'setting_category_parent_id' => '17',
            'name' => 'request.is_admin_request_user__edit_option',
            'value' => '1',
            'description' => 'Admin have the rights to enable/disable the user request edit option .',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Admin user request edit option',
            'order' => '4',
            'plugin_name' => 'Requests'
        ) ,
        array(
            'id' => '251',
            'setting_category_id' => '64',
            'setting_category_parent_id' => '17',
            'name' => 'request.auto_suspend_job_on_system_flag',
            'value' => '1',
            'description' => 'Allow suspicious word detector to suspend the work automatically.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Auto suspend Request on system flag',
            'order' => '5',
            'plugin_name' => 'Requests'
        ) ,
        array(
            'id' => '254',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'facebook.username',
            'value' => 'pages/FPPlatformUltraPlus/128576487214216?sk=wall',
            'description' => 'Facebook account of the site',
            'type' => 'text',
            'options' => '',
            'label' => 'Facebook Username',
            'order' => '9',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '257',
            'setting_category_id' => '54',
            'setting_category_parent_id' => '1',
            'name' => 'site.map_type',
            'value' => 'static',
            'description' => 'Map type when displaying map',
            'type' => 'select',
            'options' => 'static, embedd',
            'label' => 'Map Type',
            'order' => '20',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '258',
            'setting_category_id' => '18',
            'setting_category_parent_id' => '18',
            'name' => 'wallet.min_wallet_amount',
            'value' => '100',
            'description' => 'Minimum amount that can be added to wallet.',
            'type' => 'text',
            'options' => '',
            'label' => 'Maximum wallet amount',
            'order' => '1',
            'plugin_name' => 'Wallets'
        ) ,
        array(
            'id' => '259',
            'setting_category_id' => '18',
            'setting_category_parent_id' => '18',
            'name' => 'wallet.max_wallet_amount',
            'value' => '20000',
            'description' => 'Maximium amount that can be added to wallet.(Leave blank for unlimited)',
            'type' => 'text',
            'options' => '',
            'label' => 'Minimum wallet amount',
            'order' => '2',
            'plugin_name' => 'Wallets'
        ) ,
        array(
            'id' => '260',
            'setting_category_id' => '65',
            'setting_category_parent_id' => '19',
            'name' => 'dispute.discussion_threshold_for_admin_decision',
            'value' => '1',
            'description' => 'Admin will take decision, after no of conversation to buyer and seller.',
            'type' => 'text',
            'options' => '',
            'label' => 'Discussion Threshold for Admin Decision',
            'order' => '1',
            'plugin_name' => 'Disputes'
        ) ,
        array(
            'id' => '261',
            'setting_category_id' => '65',
            'setting_category_parent_id' => '19',
            'name' => 'dispute.days_left_for_disputed_user_to_reply',
            'value' => '5',
            'description' => 'Days left for disputed user to reply',
            'type' => 'text',
            'options' => '',
            'label' => 'Disputed user to reply',
            'order' => '2',
            'plugin_name' => 'Disputes'
        ) ,
        array(
            'id' => '262',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.is_show_mobile_for_offline_jobs',
            'value' => '1',
            'description' => 'Whether to show mobile number for offline jobs in view page',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Show mobile number for offline jobs in view page',
            'order' => '15',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '264',
            'setting_category_id' => '62',
            'setting_category_parent_id' => '20',
            'name' => 'affiliate.payment_threshold_for_threshold_limit_reach',
            'value' => '1',
            'description' => 'User can withdraw amount when amount reached.($)',
            'type' => 'text',
            'options' => '',
            'label' => 'Threshold limit',
            'order' => '6',
            'plugin_name' => 'Affiliates'
        ) ,
        array(
            'id' => '265',
            'setting_category_id' => '61',
            'setting_category_parent_id' => '20',
            'name' => 'affiliate.commission_holding_period',
            'value' => '0',
            'description' => 'The total number of days in which the commission amount is in holding state.',
            'type' => 'text',
            'options' => '',
            'label' => 'Commission holding period',
            'order' => '4',
            'plugin_name' => 'Affiliates'
        ) ,
        array(
            'id' => '266',
            'setting_category_id' => '61',
            'setting_category_parent_id' => '20',
            'name' => 'affiliate.commission_on_every_job_purchase',
            'value' => '1',
            'description' => 'If unchecked, the affliator earns commission on first purchase which made from signup referrals only',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Pay commission on every job purchased?',
            'order' => '3',
            'plugin_name' => 'Affiliates'
        ) ,
        array(
            'id' => '267',
            'setting_category_id' => '60',
            'setting_category_parent_id' => '20',
            'name' => 'affiliate.referral_cookie_expire_time',
            'value' => '1',
            'description' => 'Refferal cookie expire time (In Hours)',
            'type' => 'text',
            'options' => '',
            'label' => 'Affiliate referral cookie expire timing',
            'order' => '2',
            'plugin_name' => 'Affiliates'
        ) ,
        array(
            'id' => '268',
            'setting_category_id' => '62',
            'setting_category_parent_id' => '20',
            'name' => 'affiliate.site_commission_amount',
            'value' => '1',
            'description' => 'Transaction fee to be taken, When you process affiliate cash withdraw request from affiliate user. Set \'0\' to disable.',
            'type' => 'text',
            'options' => '',
            'label' => 'Transaction fee',
            'order' => '7',
            'plugin_name' => 'Affiliates'
        ) ,
        array(
            'id' => '269',
            'setting_category_id' => '62',
            'setting_category_parent_id' => '20',
            'name' => 'affiliate.site_commission_type',
            'value' => 'amount',
            'description' => 'Select the transaction fee type amount or in percentage.',
            'type' => 'select',
            'options' => 'percentage,amount',
            'label' => 'Transaction fee type',
            'order' => '8',
            'plugin_name' => 'Affiliates'
        ) ,
        array(
            'id' => '270',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.auto_accept_mutual_cancel_request',
            'value' => '2',
            'description' => 'Unanswered mutual cancellation requests will be automatically accepted after specified date. 
set \'0\' to disable this setting.',
            'type' => 'text',
            'options' => '',
            'label' => 'Auto accept mutual cancellation',
            'order' => '27',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '272',
            'setting_category_id' => '62',
            'setting_category_parent_id' => '12',
            'name' => 'user.minimum_withdrawal_amount',
            'value' => '1',
            'description' => 'Minimum amount that can be withdrawed',
            'type' => 'text',
            'options' => '',
            'label' => 'Minimum withdrawal amount',
            'order' => '1',
            'plugin_name' => 'Withdrawals'
        ) ,
        array(
            'id' => '273',
            'setting_category_id' => '62',
            'setting_category_parent_id' => '12',
            'name' => 'user.maximum_withdrawal_amount',
            'value' => '200',
            'description' => 'Maximum amount which can be withdrawned',
            'type' => 'text',
            'options' => '',
            'label' => 'Maximum withdrawal amount',
            'order' => '2',
            'plugin_name' => 'Withdrawals'
        ) ,
        array(
            'id' => '274',
            'setting_category_id' => '9',
            'setting_category_parent_id' => '41',
            'name' => 'facebook.page_id',
            'value' => '128576487214216',
            'description' => 'Facebook page ID for posting newly adding jobs in facebook page wall.',
            'type' => 'text',
            'options' => '',
            'label' => 'Facebook Page ID',
            'order' => '8',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '278',
            'setting_category_id' => '21',
            'setting_category_parent_id' => '41',
            'name' => 'google.translation_api_key',
            'value' => '123456',
            'description' => 'This is the configured Google Translate API key.',
            'type' => 'text',
            'options' => '',
            'label' => 'API Key',
            'order' => '1',
            'plugin_name' => 'Translation'
        ) ,
        array(
            'id' => '279',
            'setting_category_id' => '0',
            'setting_category_parent_id' => '0',
            'name' => 'Hook.bootstraps',
            'value' => 'SecurityQuestions,Jobs,JobFlags,JobFavorites,Wallets,Withdrawals',
            'description' => '',
            'type' => '',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '280',
            'setting_category_id' => '23',
            'setting_category_parent_id' => '22',
            'name' => 'pre_launch.bg_image',
            'value' => '',
            'description' => '(Preferred 950x552)',
            'type' => 'file',
            'options' => '',
            'label' => 'Upload Background Image',
            'order' => '6',
            'plugin_name' => 'LaunchModes'
        ) ,
        array(
            'id' => '281',
            'setting_category_id' => '23',
            'setting_category_parent_id' => '22',
            'name' => 'pre_launch.bg_image_stretch_type ',
            'value' => 'Repeat',
            'description' => 'The selected option is used for handling background image.
Repeat - Tiles the image. Stretch - Stretches the image to 100% using CSS. AutoResize - Keeps the image resized to 100% of window region using JavaScript.',
            'type' => 'select',
            'options' => 'Repeat, Stretch, AutoResize',
            'label' => 'Stretch Type ',
            'order' => '5',
            'plugin_name' => 'LaunchModes'
        ) ,
        array(
            'id' => '282',
            'setting_category_id' => '23',
            'setting_category_parent_id' => '22',
            'name' => 'site.duration_to_invite',
            'value' => 'Daily',
            'description' => 'Invitation will send within duration.',
            'type' => 'select',
            'options' => 'Daily,Weekly,Monthly',
            'label' => 'Invite Duration',
            'order' => '2',
            'plugin_name' => 'LaunchModes'
        ) ,
        array(
            'id' => '283',
            'setting_category_id' => '23',
            'setting_category_parent_id' => '22',
            'name' => 'site.no_of_users_to_invite',
            'value' => '50',
            'description' => 'If Private Beta mode is selected, users can invite friends within invite limit. Leave blank for unlimited.',
            'type' => 'text',
            'options' => '',
            'label' => 'Friends invite limit',
            'order' => '3',
            'plugin_name' => 'LaunchModes'
        ) ,
        array(
            'id' => '284',
            'setting_category_id' => '23',
            'setting_category_parent_id' => '22',
            'name' => 'site.launch_mode',
            'value' => 'Launch',
            'description' => 'If Pre-launch mode is selected, users/visitors will only be able to subscribe to your site. Only Administrator (that will be you) can access the site (e.g., http://yourdomain.com/admin). (Turn this on, when you want site traffic before launching the site.). If Private Beta mode is selected, only Administrator and users/visitors those who are having the invite code can sign up to your site and access the site, other can only able to request for invite code.',
            'type' => 'select',
            'options' => 'Pre-launch, Private Beta, Launch',
            'label' => 'Launch Mode',
            'order' => '1',
            'plugin_name' => 'LaunchModes'
        ) ,
        array(
            'id' => '285',
            'setting_category_id' => '23',
            'setting_category_parent_id' => '22',
            'name' => 'site.private_beta_content',
            'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin blandit nisi non nisl fermentum sit amet volutpat eros tincidunt. Sed tempor blandit gravida.',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Site content for private beta mode',
            'order' => '5',
            'plugin_name' => 'LaunchModes'
        ) ,
        array(
            'id' => '286',
            'setting_category_id' => '23',
            'setting_category_parent_id' => '22',
            'name' => 'site.pre_launch_content',
            'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin blandit nisi non nisl fermentum sit amet volutpat eros tincidunt. Sed tempor blandit gravida.',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Site content for pre-launch mode',
            'order' => '4',
            'plugin_name' => 'LaunchModes'
        ) ,
        array(
            'id' => '287',
            'setting_category_id' => '23',
            'setting_category_parent_id' => '22',
            'name' => 'site.no_of_users_to_invite_per_time',
            'value' => '50',
            'description' => 'If Private Beta mode is selected, subscribed users will be invited via cron in selected duration with above given limit. Leave blank for unlimited.',
            'type' => 'text',
            'options' => '',
            'label' => 'Cron invite limit',
            'order' => '4',
            'plugin_name' => 'LaunchModes'
        ) ,
        array(
            'id' => '288',
            'setting_category_id' => '24',
            'setting_category_parent_id' => '41',
            'name' => 'google_analytics.access_token',
            'value' => '',
            'description' => 'This will be automatically updated when \"Update Google Analytics Credentials\" link is clicked. (Required for get data from Google Analytics)',
            'type' => 'text',
            'options' => '',
            'label' => 'Access Token',
            'order' => '5',
            'plugin_name' => 'IntegratedGoogleAnalytics'
        ) ,
        array(
            'id' => '289',
            'setting_category_id' => '24',
            'setting_category_parent_id' => '41',
            'name' => 'google_analytics.profile_id',
            'value' => '63232568',
            'description' => 'This is the Profile ID to fetch data from Google Analytics. Please refer this <a href=\"##ANALYTICS_IMAGE##\" target=\"_blank\">image</a>. Example: p\'XXXX\'.',
            'type' => 'text',
            'options' => '',
            'label' => 'Profile ID',
            'order' => '4',
            'plugin_name' => 'IntegratedGoogleAnalytics'
        ) ,
        array(
            'id' => '290',
            'setting_category_id' => '32',
            'setting_category_parent_id' => '25',
            'name' => 'HtmlCache.is_htmlcache_enabled',
            'value' => '1',
            'description' => '',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Full-page Caching',
            'order' => '3',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '291',
            'setting_category_id' => '30',
            'setting_category_parent_id' => '25',
            'name' => 'RedisSession.is_redis_session_enabled',
            'value' => '0',
            'description' => '',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Redis',
            'order' => '7',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '292',
            'setting_category_id' => '30',
            'setting_category_parent_id' => '25',
            'name' => 'RedisSession.RedisSession.hostname',
            'value' => '',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Redis Host Name',
            'order' => '8',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '293',
            'setting_category_id' => '30',
            'setting_category_parent_id' => '25',
            'name' => 'RedisSession.port',
            'value' => '',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Redis Port',
            'order' => '9',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '294',
            'setting_category_id' => '31',
            'setting_category_parent_id' => '25',
            'name' => 'Memcached.is_memcached_enabled',
            'value' => '0',
            'description' => '',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Memcached',
            'order' => '1',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '295',
            'setting_category_id' => '31',
            'setting_category_parent_id' => '25',
            'name' => 'Memcached.servers',
            'value' => '',
            'description' => 'Add multiple server host name (seperated by comma)',
            'type' => 'text',
            'options' => '',
            'label' => 'Memcached Servers',
            'order' => '2',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '299',
            'setting_category_id' => '28',
            'setting_category_parent_id' => '25',
            'name' => 'cdn.images',
            'value' => '',
            'description' => 'This is base URL (without trailing slash) for CDN images. (e.g., http://images.yourdomain.com)',
            'type' => 'text',
            'options' => '',
            'label' => 'CDN Image URL',
            'order' => '2',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '300',
            'setting_category_id' => '28',
            'setting_category_parent_id' => '25',
            'name' => 'cdn.css',
            'value' => '',
            'description' => 'This is base URL (without trailing slash) for CDN CSS. (e.g., http://css.yourdomain.com)',
            'type' => 'text',
            'options' => '',
            'label' => 'CDN CSS URL',
            'order' => '3',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '301',
            'setting_category_id' => '28',
            'setting_category_parent_id' => '25',
            'name' => 'cdn.js',
            'value' => '',
            'description' => 'This is base URL (without trailing slash) for CDN JavaScript. (e.g., http://js.yourdomain.com)',
            'type' => 'text',
            'options' => '',
            'label' => 'CDN JS URL',
            'order' => '4',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '302',
            'setting_category_id' => '28',
            'setting_category_parent_id' => '25',
            'name' => 'cdn.is_cdn_enabled',
            'value' => '0',
            'description' => '',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Pull CDN',
            'order' => '1',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '303',
            'setting_category_id' => '29',
            'setting_category_parent_id' => '25',
            'name' => 'mail.is_smtp_enabled',
            'value' => '0',
            'description' => '',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable SMTP server',
            'order' => '1',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '304',
            'setting_category_id' => '29',
            'setting_category_parent_id' => '25',
            'name' => 'mail.smtp_host',
            'value' => '0',
            'description' => 'Add like ssl://smtp.gmail.com <http://smtp.gmail.com> host name',
            'type' => 'text',
            'options' => '',
            'label' => 'SMTP host',
            'order' => '2',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '305',
            'setting_category_id' => '29',
            'setting_category_parent_id' => '25',
            'name' => 'mail.mail.smtp_port',
            'value' => '465',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'SMTP port',
            'order' => '3',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '306',
            'setting_category_id' => '29',
            'setting_category_parent_id' => '25',
            'name' => 'mail.smtp_username',
            'value' => '',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'SMTP username',
            'order' => '4',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '307',
            'setting_category_id' => '34',
            'setting_category_parent_id' => '41',
            'name' => 'google.consumer_key',
            'value' => '',
            'description' => 'This is the Consumer ID used in Gmail share.',
            'type' => 'text',
            'options' => '',
            'label' => 'Consumer ID',
            'order' => '2',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '308',
            'setting_category_id' => '34',
            'setting_category_parent_id' => '41',
            'name' => 'google.consumer_secret',
            'value' => '',
            'description' => 'This is the Secrete key used in Gmail share.',
            'type' => 'text',
            'options' => '',
            'label' => 'Client Secret',
            'order' => '2',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '309',
            'setting_category_id' => '35',
            'setting_category_parent_id' => '41',
            'name' => 'yahoo.consumer_key',
            'value' => '',
            'description' => 'This is the Consumer Key is used in Yahoo! share.',
            'type' => 'text',
            'options' => '',
            'label' => 'Consumer Key',
            'order' => '4',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '310',
            'setting_category_id' => '35',
            'setting_category_parent_id' => '41',
            'name' => 'yahoo.consumer_secret',
            'value' => '',
            'description' => 'This is the Consumer Secret Key is used in Yahoo! share.',
            'type' => 'text',
            'options' => '',
            'label' => 'Consumer Secret',
            'order' => '5',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '311',
            'setting_category_id' => '37',
            'setting_category_parent_id' => '41',
            'name' => 'linkedin.consumer_key',
            'value' => '',
            'description' => 'This is the Consumer Key used in LinkedIn share.',
            'type' => 'text',
            'options' => '',
            'label' => 'Consumer Key',
            'order' => '4',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '312',
            'setting_category_id' => '37',
            'setting_category_parent_id' => '41',
            'name' => 'linkedin.consumer_secret',
            'value' => '',
            'description' => 'This is the Secret Key used in LinkedIn share.',
            'type' => 'text',
            'options' => '',
            'label' => 'Consumer Secret',
            'order' => '4',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '313',
            'setting_category_id' => '33',
            'setting_category_parent_id' => '51',
            'name' => 'share.facebook',
            'value' => 'Check out this website ##SITE_NAME## ##SHARE_URL##',
            'description' => '##SITE_NAME## ##SHARE_URL##',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Facebook Share content ',
            'order' => '0',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '314',
            'setting_category_id' => '33',
            'setting_category_parent_id' => '51',
            'name' => 'share.twitter',
            'value' => 'Check out this project ##JOB_NAME##',
            'description' => '##JOB_NAME## ##SHARE_URL##',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Twitter Share content',
            'order' => '0',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '315',
            'setting_category_id' => '38',
            'setting_category_parent_id' => '41',
            'name' => 'googleplus.consumer_secret',
            'value' => '',
            'description' => 'This is the Secrete key used in Google+ share.',
            'type' => 'text',
            'options' => '',
            'label' => 'Secret key',
            'order' => '2',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '316',
            'setting_category_id' => '38',
            'setting_category_parent_id' => '41',
            'name' => 'googleplus.consumer_key',
            'value' => '',
            'description' => 'This is the Consumer ID used in Google+ share.',
            'type' => 'text',
            'options' => '',
            'label' => 'Consumer ID',
            'order' => '2',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '320',
            'setting_category_id' => '40',
            'setting_category_parent_id' => '58',
            'name' => 'googleplus.is_enabled_googleplus_connect',
            'value' => '1',
            'description' => 'By enabling this feature, users can authenticate their ##SITE_NAME## account using Google+.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Google+',
            'order' => '4',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '321',
            'setting_category_id' => '40',
            'setting_category_parent_id' => '58',
            'name' => 'linkedin.is_enabled_linkedin_connect',
            'value' => '1',
            'description' => 'By enabling this feature, users can authenticate their ##SITE_NAME## account using Linkedin.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Linkedin',
            'order' => '7',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '322',
            'setting_category_id' => '40',
            'setting_category_parent_id' => '58',
            'name' => 'yahoo.is_enabled_yahoo_connect',
            'value' => '1',
            'description' => 'By enabling this feature, users can authenticate their ##SITE_NAME## account using Yahoo!.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Yahoo!',
            'order' => '5',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '323',
            'setting_category_id' => '40',
            'setting_category_parent_id' => '58',
            'name' => 'google.is_enabled_google_connect',
            'value' => '1',
            'description' => 'By enabling this feature, users can authenticate their ##SITE_NAME## account using Google.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Google',
            'order' => '4',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '324',
            'setting_category_id' => '40',
            'setting_category_parent_id' => '58',
            'name' => 'twitter.is_enabled_twitter_connect',
            'value' => '1',
            'description' => 'By enabling this feature, users can authenticate their ##SITE_NAME## account using Twitter.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Twitter',
            'order' => '4',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '325',
            'setting_category_id' => '40',
            'setting_category_parent_id' => '58',
            'name' => 'openid.is_enabled_openid_connect',
            'value' => '1',
            'description' => 'By enabling this feature, users can authenticate their ##SITE_NAME## account using OpenID.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable OpenID',
            'order' => '2',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '326',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.large_thumb.height',
            'value' => '170',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '327',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.large_thumb.width',
            'value' => '170',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => '',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '328',
            'setting_category_id' => '47',
            'setting_category_parent_id' => '25',
            'name' => 's3.is_enabled',
            'value' => '0',
            'description' => 'Uncheck this to revert back to using your own web host for storage and delivery at anytime',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable storing of files to Amazon S3 and serving files from Amazon S3',
            'order' => '10',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '330',
            'setting_category_id' => '47',
            'setting_category_parent_id' => '25',
            'name' => 's3.aws_access_key',
            'value' => 'AKIAJXCSPWSJ7BN3HYBQ',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Access Key',
            'order' => '12',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '331',
            'setting_category_id' => '47',
            'setting_category_parent_id' => '25',
            'name' => 's3.aws_secret_key',
            'value' => 'W/AW/y1w82BudV1qw9OwtH3KgjtxE8umJNvpfq5l',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Secret Key',
            'order' => '13',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '332',
            'setting_category_id' => '47',
            'setting_category_parent_id' => '25',
            'name' => 's3.bucket_name',
            'value' => 'fpplatform',
            'description' => '##TEST_CONNECTION##',
            'type' => 'text',
            'options' => '',
            'label' => 'Bucket Name',
            'order' => '14',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '333',
            'setting_category_id' => '47',
            'setting_category_parent_id' => '25',
            'name' => 's3.keep_copy_in_local',
            'value' => '0',
            'description' => '',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Keep copy in local',
            'order' => '15',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '334',
            'setting_category_id' => '47',
            'setting_category_parent_id' => '25',
            'name' => 's3.is_cname_enabled',
            'value' => '0',
            'description' => 'For more details please refer <a title=\"For more info\" target=\"_blank\" href=\"http://docs.amazonwebservices.com/AmazonS3/2006-03-01/VirtualHosting.html\">http://docs.amazonwebservices.com/AmazonS3/2006-03-01/VirtualHosting.html</a>',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Bucket is setup for virtual hosting',
            'order' => '16',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '335',
            'setting_category_id' => '47',
            'setting_category_parent_id' => '25',
            'name' => 's3.upload_static_content_enabled',
            'value' => '0',
            'description' => 'Static content such as CSS, JavaScript, images files in <code>webroot</code> folder. Uncheck this to revert back to using own server for delivery at anytime.',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable to deliver all the static contents from Amazon S3',
            'order' => '17',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '336',
            'setting_category_id' => '47',
            'setting_category_parent_id' => '25',
            'name' => 's3.end_point',
            'value' => 's3-us-west-2.amazonaws.com',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'End Point',
            'order' => '15',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '337',
            'setting_category_id' => '26',
            'setting_category_parent_id' => '25',
            'name' => 'cloudflare.is_cloudflare_enabled',
            'value' => '0',
            'description' => '',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable CloudFlare',
            'order' => '1',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '338',
            'setting_category_id' => '26',
            'setting_category_parent_id' => '25',
            'name' => 'cloudflare.token',
            'value' => '',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'CloudFlare Token',
            'order' => '3',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '339',
            'setting_category_id' => '26',
            'setting_category_parent_id' => '25',
            'name' => 'cloudflare.email',
            'value' => '',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'CloudFlare Email Id',
            'order' => '2',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '340',
            'setting_category_id' => '29',
            'setting_category_parent_id' => '25',
            'name' => 'mail.smtp_password',
            'value' => '',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'SMTP password',
            'order' => '5',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '341',
            'setting_category_id' => '27',
            'setting_category_parent_id' => '25',
            'name' => 'is_page_speed_enabled',
            'value' => '1',
            'description' => '',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Google page speed',
            'order' => '0',
            'plugin_name' => 'HighPerformance'
        ) ,
        array(
            'id' => '342',
            'setting_category_id' => '49',
            'setting_category_parent_id' => '1',
            'name' => 'system.captcha_type',
            'value' => 'Normal',
            'description' => 'The selected type will be used for CAPTCHA display in sign up and contact us pages.',
            'type' => 'select',
            'options' => 'Normal,Solve Media',
            'label' => 'CAPTCHA Type',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '343',
            'setting_category_id' => '50',
            'setting_category_parent_id' => '41',
            'name' => 'captcha.challenge_key',
            'value' => 'oR.X9IGEcuYNu3pk7m.ZN7BiD-M-vHFp',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Challenge Key',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '344',
            'setting_category_id' => '50',
            'setting_category_parent_id' => '41',
            'name' => 'captcha.verification_key',
            'value' => '00MsxSO3v0GQRB8TFPla0rY9dzeovpSd',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Verification Key',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '345',
            'setting_category_id' => '50',
            'setting_category_parent_id' => '41',
            'name' => 'captcha.hash_key',
            'value' => 'G9VT4C021Q1ExAKN8Wltf.cxMX-V9wfG',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Authentication Hash Key',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '346',
            'setting_category_id' => '59',
            'setting_category_parent_id' => '58',
            'name' => 'user.is_enable_forgot_password_captcha',
            'value' => '1',
            'description' => 'Here you can enable captcha when user request for forgot password',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Captcha when Forgot Password',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '347',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.is_enable_online',
            'value' => '1',
            'description' => 'Specify online project is allowed or not',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Online Job',
            'order' => '1',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '348',
            'setting_category_id' => '63',
            'setting_category_parent_id' => '4',
            'name' => 'job.is_enable_offline',
            'value' => '1',
            'description' => 'Specify offline project is allowed or not',
            'type' => 'checkbox',
            'options' => '',
            'label' => 'Enable Offline Job',
            'order' => '1',
            'plugin_name' => 'Jobs'
        ) ,
        array(
            'id' => '349',
            'setting_category_id' => '68',
            'setting_category_parent_id' => '67',
            'name' => 'widget.footer_script',
            'value' => '<img src=\"http://placehold.it/728X90\" alt =\"728X90\" width=\"728\" height=\"90\"/>',
            'description' => 'This is the footer page script, used for display banners on footer page',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Code',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '350',
            'setting_category_id' => '69',
            'setting_category_parent_id' => '67',
            'name' => 'widget.job_script',
            'value' => '',
            'description' => 'This is the job page script, used for display banners on Job view page',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Code',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '351',
            'setting_category_id' => '70',
            'setting_category_parent_id' => '67',
            'name' => 'widget.request_script',
            'value' => '',
            'description' => 'This is the request view page script, used for display banners on request view page',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Code',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '352',
            'setting_category_id' => '71',
            'setting_category_parent_id' => '67',
            'name' => 'widget.user_script',
            'value' => '<img src=\"http://placehold.it/728X90\" alt =\"728X90\" width=\"728\" height=\"90\"/>',
            'description' => 'This is the user page script, used for display banners on user page',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Code',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '353',
            'setting_category_id' => '15',
            'setting_category_parent_id' => '51',
            'name' => 'invite.facebook',
            'value' => 'Check out this website ##SITE_NAME## ##REFERRAL_URL##',
            'description' => '##SITE_NAME## ##REFERRAL_URL##',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Invite Facebook Content',
            'order' => '0',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '354',
            'setting_category_id' => '15',
            'setting_category_parent_id' => '51',
            'name' => 'invite.twitter',
            'value' => 'Check out this website ##SITE_NAME## ##REFERRAL_URL##',
            'description' => '##SITE_NAME## ##REFERRAL_URL##',
            'type' => 'textarea',
            'options' => '',
            'label' => 'Invite Twitter Content',
            'order' => '0',
            'plugin_name' => 'SocialMarketing'
        ) ,
        array(
            'id' => '355',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.medium_large_thumb.width',
            'value' => '230',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Medium large thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
        array(
            'id' => '356',
            'setting_category_id' => '7',
            'setting_category_parent_id' => '0',
            'name' => 'thumb_size.medium_large_thumb.height',
            'value' => '202',
            'description' => '',
            'type' => 'text',
            'options' => '',
            'label' => 'Medium large thumb',
            'order' => '0',
            'plugin_name' => ''
        ) ,
    );
}
